name: Build

on:
  push:
  pull_request:
    branches:
      - master     

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules:  'true'
          fetch-depth: 0
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.14" 
          CIBW_BUILD: "cp39-*"
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
